# Generated by cpp11: do not edit by hand

mod_name_ <- function(mod) {
  .Call(`_ProTrackR2_mod_name_`, mod)
}

mod_length_ <- function(mod) {
  .Call(`_ProTrackR2_mod_length_`, mod)
}

set_mod_length_ <- function(mod, modlen) {
  .Call(`_ProTrackR2_set_mod_length_`, mod, modlen)
}

mod_pattab_ <- function(mod) {
  .Call(`_ProTrackR2_mod_pattab_`, mod)
}

update_pattern_sequence_ <- function(mod, ptn_sequence) {
  .Call(`_ProTrackR2_update_pattern_sequence_`, mod, ptn_sequence)
}

set_mod_name_ <- function(mod, name) {
  .Call(`_ProTrackR2_set_mod_name_`, mod, name)
}

open_mod_ <- function(data) {
  .Call(`_ProTrackR2_open_mod_`, data)
}

mod_as_raw_ <- function(mod) {
  .Call(`_ProTrackR2_mod_as_raw_`, mod)
}

new_mod_ <- function(name) {
  .Call(`_ProTrackR2_new_mod_`, name)
}

render_mod_ <- function(mod, render_duration, render_options, position) {
  .Call(`_ProTrackR2_render_mod_`, mod, render_duration, render_options, position)
}

mod_duration <- function(mod, render_options, position) {
  .Call(`_ProTrackR2_mod_duration`, mod, render_options, position)
}

pt_get_PAL_hz <- function() {
  .Call(`_ProTrackR2_pt_get_PAL_hz`)
}

cells_as_raw_ <- function(mod, pattern, compact, row, channel) {
  .Call(`_ProTrackR2_cells_as_raw_`, mod, pattern, compact, row, channel)
}

set_new_pattern_ <- function(mod, pattern_idx, data_new) {
  .Call(`_ProTrackR2_set_new_pattern_`, mod, pattern_idx, data_new)
}

pt_cell_bytesize <- function() {
  .Call(`_ProTrackR2_pt_cell_bytesize`)
}

note_to_period_ <- function(note, empty_char, finetune) {
  .Call(`_ProTrackR2_note_to_period_`, note, empty_char, finetune)
}

pt_note_string_raw_ <- function(data) {
  .Call(`_ProTrackR2_pt_note_string_raw_`, data)
}

pt_rawcell_as_char_ <- function(pattern, padding, empty_char, sformat) {
  .Call(`_ProTrackR2_pt_rawcell_as_char_`, pattern, padding, empty_char, sformat)
}

pt_decode_compact_cell <- function(source) {
  .Call(`_ProTrackR2_pt_decode_compact_cell`, source)
}

pt_encode_compact_cell <- function(source) {
  .Call(`_ProTrackR2_pt_encode_compact_cell`, source)
}

pt_cleanup_ <- function() {
  .Call(`_ProTrackR2_pt_cleanup_`)
}

pt_init_ <- function() {
  .Call(`_ProTrackR2_pt_init_`)
}

open_samp_ <- function(data) {
  .Call(`_ProTrackR2_open_samp_`, data)
}

sample_file_format_ <- function(input, file_type) {
  .Call(`_ProTrackR2_sample_file_format_`, input, file_type)
}

mod_sample_as_raw_ <- function(mod, idx) {
  .Call(`_ProTrackR2_mod_sample_as_raw_`, mod, idx)
}

mod_sample_info_ <- function(mod, idx) {
  .Call(`_ProTrackR2_mod_sample_info_`, mod, idx)
}

mod_sample_as_int_ <- function(mod, idx) {
  .Call(`_ProTrackR2_mod_sample_as_int_`, mod, idx)
}

validate_sample_raw_ <- function(smp_data) {
  .Call(`_ProTrackR2_validate_sample_raw_`, smp_data)
}

mod_set_sample_ <- function(mod, idx, smp_data) {
  .Call(`_ProTrackR2_mod_set_sample_`, mod, idx, smp_data)
}
