# Generated by cpp11: do not edit by hand

mod_name_ <- function(mod) {
  .Call(`_ProTrackR2_mod_name_`, mod)
}

mod_length_ <- function(mod) {
  .Call(`_ProTrackR2_mod_length_`, mod)
}

mod_pattab_ <- function(mod) {
  .Call(`_ProTrackR2_mod_pattab_`, mod)
}

open_mod_ <- function(data) {
  .Call(`_ProTrackR2_open_mod_`, data)
}

mod_as_raw_ <- function(mod) {
  .Call(`_ProTrackR2_mod_as_raw_`, mod)
}

new_mod_ <- function(name) {
  .Call(`_ProTrackR2_new_mod_`, name)
}

render_mod_ <- function(mod, render_duration, render_options) {
  .Call(`_ProTrackR2_render_mod_`, mod, render_duration, render_options)
}

pattern_as_raw_ <- function(mod, pattern, compact) {
  .Call(`_ProTrackR2_pattern_as_raw_`, mod, pattern, compact)
}

pt_cell_ <- function(mod, pattern, channel, row) {
  .Call(`_ProTrackR2_pt_cell_`, mod, pattern, channel, row)
}

pt_cell_as_char_ <- function(mod, pattern, channel, row, padding, empty_char, sformat) {
  .Call(`_ProTrackR2_pt_cell_as_char_`, mod, pattern, channel, row, padding, empty_char, sformat)
}

pt_rawcell_as_char_ <- function(pattern, padding, empty_char, sformat) {
  .Call(`_ProTrackR2_pt_rawcell_as_char_`, pattern, padding, empty_char, sformat)
}

pt_decode_compact_cell <- function(source) {
  .Call(`_ProTrackR2_pt_decode_compact_cell`, source)
}

pt_encode_compact_cell <- function(source) {
  .Call(`_ProTrackR2_pt_encode_compact_cell`, source)
}

pt_cleanup_ <- function() {
  .Call(`_ProTrackR2_pt_cleanup_`)
}

pt_init_ <- function() {
  .Call(`_ProTrackR2_pt_init_`)
}

open_samp_ <- function(data) {
  .Call(`_ProTrackR2_open_samp_`, data)
}

sample_file_format_ <- function(input, file_type) {
  .Call(`_ProTrackR2_sample_file_format_`, input, file_type)
}

mod_sample_as_raw_ <- function(mod, idx) {
  .Call(`_ProTrackR2_mod_sample_as_raw_`, mod, idx)
}

mod_sample_info_ <- function(mod, idx) {
  .Call(`_ProTrackR2_mod_sample_info_`, mod, idx)
}

mod_sample_as_int_ <- function(mod, idx) {
  .Call(`_ProTrackR2_mod_sample_as_int_`, mod, idx)
}
